### ISSUE TITLE
Using this with Home Assistant

### ISSUE THREAD

**Issue by sillyfrog** [akirjavainen/markisol#2]
Great, project, thanks for publishing!

Not an issue, but an FYI. I have built a project on top of your work to allow me to control my blinds with Home Assistant. The first part is here: https://github.com/sillyfrog/homie_blind_control . This runs on an ESP8266 and controls the actual hardware. It also provides a simple Web Interface to emulate a remote control.

There is then a manager to manage several controllers and integrate with Home Assistant here: https://github.com/sillyfrog/blindsmanager

Thanks again!

**Comment by akirjavainen** [comment]
Thank you for messaging me and it's great to hear you've found my project useful! Put it to good use. :)
